toc:
  - name: Plugins
    description: |
      Restify comes bundled with a selection of useful plugins. These are accessible
      off of `restify.plugins` and `restify.pre`.
  - auditLogger
  - createMetrics
  - jsonp
  - name: Types
  - createMetrics~callback
